name: Deploy to GCP VM

on:
  push:
    branches:
      - develop

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.check.outputs.changed_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Get PR number and check changed files
        id: check
        env:
          GH_TOKEN: ${{ secrets.JEGANMERGE }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          echo "PR Number: $pr_number"
          changed_files=$(gh pr view "$pr_number" --json files --jq '.files[].path')
          echo "Changed files from gh command: $changed_files"
          changed_files_single_line=$(echo "$changed_files" | tr '\n' ' ')
          echo "changed_files=$changed_files_single_line" >> $GITHUB_ENV
          echo "::set-output name=changed_files::$changed_files_single_line"

  deploy:
    runs-on: ubuntu-latest
    needs: list-files  # Ensure this job waits for the list-files job to complete

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.MY_FILE_SECRET }}
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

    - name: Decode Google Cloud key
      run: echo "${{ secrets.MY_FILE_SECRET }}" | base64 --decode > service-account.json
      
    - name: Authenticate to GCP
      run: |
        gcloud auth activate-service-account --key-file=service-account.json
        gcloud config set project ${{ secrets.GOOGLE_CLOUD_PROJECT }}
      
    - name: Deploy changed files
      run: |
        changed_files="${{ needs.list-files.outputs.changed_files }}"
        if [ -z "$changed_files" ]; then
          echo "No files to deploy."
          exit 0
        fi
        files=($changed_files)
        for file in "${files[@]}"; do
            echo "Deploying $file to your specific VM"
            gcloud compute scp "$file" "${{ secrets.REMOTE_USER_GCP }}@${{ secrets.GITHUB_INSTANCE }}:${{ secrets.DEPLOY_PATH }}/$file" --zone=${{ secrets.GOOGLE_CLOUD_ZONE }} --project=${{ secrets.GOOGLE_CLOUD_PROJECT }}
        done

    env:
      DEPLOY_PATH: /home/Jegan/www_profitokrs_com_6_4_1
      BACKUP_PATH: /home/Jegan/profit-site-en-backup
      DATE: $(date +'%Y%m%d_%H%M%S')
