name: List and Deploy PR Changed Files

on:

  issues:
    types: [opened, edited]

jobs:
  check-issue:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.check_approval.outputs.approved }}  # Pass output from approval check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if issue is approved
        id: check_approval
        env:
          GH_TOKEN: ${{ secrets.JEGANMERGE }}
        run: |
          issue_number="${{ github.event.issue.number }}"
          
          # Fetch labels of the issue using GitHub CLI
          labels=$(gh issue view "$issue_number" --json labels --jq '.labels[].name' || echo "Error fetching labels")
          
          echo "Labels: $labels"  # Debugging output
          
          # Check if the "APPROVED" label is present
          if [[ "$labels" == *"APPROVED"* ]]; then
            echo "Issue approved."
            echo "approved=true" >> $GITHUB_ENV
            echo "approved=true" >> $GITHUB_OUTPUT
          else
            echo "Issue not approved. Exiting."
            echo "approved=false" >> $GITHUB_ENV
            echo "approved=false" >> $GITHUB_OUTPUT
            exit 1
          fi
